config/routes.rb
Rails.application.routes.draw do


  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end


  # ユーザー用
# URL /user/sign_in ...
devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: "public/sessions"
}


 scope module: :public do
  root to: "homes#top"
  get "/home/about" => "homes#about", as: "about"
  get "relationships/followings"
  get "relationships/followers"
  get "/article/hashtag/:name", to: "articles#hashtag"
  get "search" => "searches#search"
  get "users/unsubscribe" => "users#unsubscribe", as: "unsubscribe"
  patch "users/withdrawal" => "users#withdrawal", as: "withdrawal"
  get "chat/:id" => "chats#show", as: "chat"
  resources :chats, only: [:create]


 resources :articles, only: [:new,:index,:show,:edit,:create,:destroy,:update] do
   resources :article_comments, only:[:create, :destroy]
   resource :favorites, only: [:create, :destroy,]
 end

  resources :users, only: [:index,:show,:edit,:update] do
     member do
      get :favorites
    end
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
 end

end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
   root to: "homes#top"
   resources :articles, only: [:index, :show, :edit, :update, :destroy]
   resources :users, only: [:index, :show, :edit, :update]
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  belongs_to :user
  has_many :article_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :article_hashtags
  has_many :hashtags, through: :article_hashtags
  has_many :tags, dependent: :destroy

  has_one_attached :article_image



  def get_article_image
    (article_image.attached?) ? article_image : "no_image.jpg"
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

    after_create do
    article = Article.find_by(id: id)
    hashtags  = body.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    article.hashtags = []
    hashtags.uniq.map do |hashtag|
      #ハッシュタグは先頭の'#'を外した上で保存
      tag = Hashtag.find_or_create_by(name_tag: hashtag.downcase.delete("#"))
      article.hashtags << tag
    end
  end

  before_update do
    article = Article.find_by(id: id)
    article.hashtags.clear
    hashtags = body.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      tag = Hashtag.find_or_create_by(name_tag: hashtag.downcase.delete("#"))
      article.hashtags << tag
    end
  end

  def get_latitude
    return 35.6877479 if self.latitude == nil
    return self.latitude
  end

  def get_longitude
    return 139.7676993 if self.longitude == nil
    return self.longitude
  end

 def self.looks(word)
    # if search == "perfect_match"
    #   @article = Article.where("title LIKE?","#{word}")
    # elsif search == "forward_match"
    #   @article = Article.where("title LIKE?","#{word}%")
    # elsif search == "backward_match"
    #    @article = Article.where("title LIKE?","%#{word}")
    # elsif search == "partial_match"
      @article = Article.where("title LIKE?","%#{word}%")
    # else
    #   @article = Article.all
    # end
 end
 
 scope :created_today, -> { where(created_at: Time.zone.now.all_day) } 
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) } 
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) } 
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) } 
  
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
 before_action :authenticate_admin!


  def index
    @articles = Article.order(created_at: :desc).page(params[:page]).per(9)
    @arttile = Article.new
    @user = current_user
  end

  def show
    @article = Article.find(params[:id])
    # @user = User.find(params[:id])
    @article_comment = ArticleComment.new
  end

  def edit
     @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to admin_article_path(@article), notice: "更新に成功しました"
    else
      render "edit"
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to admin_articles_path
  end

   private
  def article_params
    #byebug
    params.require(:article).permit(:title, :body, :article_image, :latitude, :longitude)
  end

end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/views/admin/articles/edit.html.erb
<%= render 'layouts/errors', obj: @article %>
<%= form_with model: @article, url: admin_article_path(@article),local:true do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control article_title' %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control article_body' %>
  </div>
  <!-- 追加部分 -->
   <div class="form-group">
  <%= f.label :image %>
  <%= f.file_field :article_image, accept: "image/*" %>
  </div>

  <div>ロケーション</div>
  <input id="address" type="textbox" value="">
  <%= f.hidden_field :latitude %>
  <%= f.hidden_field :longitude %>

<!-- buttonをクリックしたらcodeAddressを実行　-->
<input type="button" value="search" onclick="codeAddress()">
<div id='map'></div>

<style>
#map{
  height: 400px;
}
</style>

<script>
let map
let geocoder

function initMap(){
  // geocoderを初期化
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
  center: {lat: <%= @article.get_latitude %>, lng: <%= @article.get_longitude %>},
  zoom: 8
  });
}

function codeAddress(){
  // 入力を取得
  let inputAddress = document.getElementById('address').value;

  // geocodingしたあとmapを移動
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
　　　　　　　　　　　　// map.setCenterで地図が移動
　　　console.log(results[0])
      map.setCenter(results[0].geometry.location);
      document.getElementById("article_latitude").value = results[0].geometry.location.lat();
      document.getElementById("article_longitude").value = results[0].geometry.location.lng();

　　　　　　　　　　　　// google.maps.MarkerでGoogleMap上の指定位置にマーカが立つ
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
    } else {
      alert('Geocode was not successful for the following reason: ' + status);
    }
  });
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['SECRET_KEY'] %>&callback=initMap" async defer></script>

  <div class="form-group my-2">
    <%= f.submit '修正する', class: "btn btn-success" %>
  </div>

<% end %>

app/views/admin/articles/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
        <h2 class="text-center border-bottom my-2">Articles</h2>

      <!--<div style="display: flex; align-items: flex-end;">-->
      <!--</div>-->
      <div class="row">
        <% @articles.each do |article|%>
        <div class="col-md-4">
          <div class="card m-2 text-center card-warpper">
            <%= link_to admin_article_path(article.id) do %>
              <%= image_tag article.get_article_image, class:"card-img-top index-img" %>
                 <% end %>
              <div class="card-body text-dark py-2 font-weight-bold ">
                <%= link_to article.title, admin_article_path(article.id), class: "card-title mb-2" %>
              </div>
             <div class ="time">投稿日時：<%= l article.created_at, format: :short %></div>
             <div>created by : <%= link_to edit_admin_user_path(article.user) do %>
              <%= image_tag article.user.get_profile_image, class: "rounded-circle border border-darkS", size:'30x30' %>
              <% end %>
             </div>

          </div>
        </div>
        <% end %>
      </div>
      <div class="text-center">
        <%= paginate @articles %>
      </div>
    </div>
  </div>
</div>

app/views/admin/articles/show.html.erb
<div class='container'>
  <div class='row'>
     <div class="col-md-12"  style="margin-top: 10px;">
<p class="text-center border-bottom">詳細画面</p>
<div class="card m-2 text-center card-warpper　">
   <%= image_tag @article.get_article_image, size:'300x300', class:"d-block mx-auto" %>
  <div class="card-body">
    <h2 class="card-title "><%= @article.title %></h2>
    <%= render_with_hashtags(@article.body) %>
  </div>

<h4>ロケーション</h4>
<div id='map'></div>

<style>
#map{
  height: 200px;
}
</style>

<script>
function initMap(){
  let map = new google.maps.Map(document.getElementById('map'), {
  center: {lat: <%= @article.get_latitude %>, lng: <%= @article.get_longitude %>},
  zoom: 8
  });

  var marker = new google.maps.Marker({
          map: map,

          position: {lat: <%= @article.get_latitude %>, lng: <%= @article.get_longitude %>},
      });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['SECRET_KEY'] %>&callback=initMap" async defer></script>


<!--<div class="favorites mt-2">-->
<!--<div id="favorite_buttons_<%##= render "public/favorites/favorite", article: @article %>-->
<!--　　</div>-->
<!--　　</div>-->


    <%= form_with model: [@article, @article_comment], local: false do |f| %>
      <div><%= f.text_area :comment, rows: '5', placeholder: "comment", class: "form-control" %> </div>
      <div><%= f.submit "送信", class: "btn btn-primary" %></div>
        <% end %>
   <%# if @article.user == current_user %>
    <%= link_to '編集', edit_admin_article_path(@article), class: "btn btn-sm btn-success" %>
    <%= link_to '削除', admin_article_path(@article), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%>
   <%# end %>

</div>

  </div>
   </div>
   </div>