config/routes.rb
Rails.application.routes.draw do


  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end


  # ユーザー用
# URL /user/sign_in ...
devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: "public/sessions"
}


 scope module: :public do
  root to: "homes#top"
  get "/home/about" => "homes#about", as: "about"
  get "relationships/followings"
  get "relationships/followers"
  get "/article/hashtag/:name", to: "articles#hashtag"
  get "search" => "searches#search"
  get "users/unsubscribe" => "users#unsubscribe", as: "unsubscribe"
  patch "users/withdrawal" => "users#withdrawal", as: "withdrawal"
  get "chat/:id" => "chats#show", as: "chat"
  resources :chats, only: [:create]


 resources :articles, only: [:new,:index,:show,:edit,:create,:destroy,:update] do
   resources :article_comments, only:[:create, :destroy]
   resource :favorites, only: [:create, :destroy,]
 end

  resources :users, only: [:index,:show,:edit,:update] do
     member do
      get :favorites
    end
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
 end

end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
   root to: "homes#top"
   resources :articles, only: [:index, :show, :edit, :update, :destroy]
   resources :users, only: [:index, :show, :edit, :update]
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true, presence: true
  validates :introduction, length: { maximum: 50 }

  has_many :articles, dependent: :destroy
  has_many :article_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :user_rooms
  has_many :chats

    # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

 has_one_attached :profile_image



  def get_profile_image
    (profile_image.attached?) ? profile_image : "no_image.jpg"
  end

  def country
    Carmen::Country.coded(country_code)
  end

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def self.looks(word)
    # if search == "perfect_match"
    #   @user = User.where("name LIKE?", "#{word}")
    # elsif search == "forward_match"
    #   @user = User.where("name LIKE?","#{word}%")
    # elsif search == "backward_match"
    #   @user = User.where("name LIKE?","%#{word}")
    # elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    # else
    #   @user = User.all
    # end
  end

  def self.guest
    find_or_create_by!(name: "guestuser" ,email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
 before_action :authenticate_admin!


  def index
    @users = User.page(params[:page])
    @article = Article.new

  end

  def show
    @user = User.find(params[:id])
    @articles = @user.articles.page(params[:page])
    @article = Article.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
      @user =  User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "更新に成功しました"
    else
      render :edit
    end
  end

  def withdrawal
    @user = User.find(current_user.id)
    # is_deletedカラムをtrueに変更することにより削除フラグを立てる
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :country_code, :abroad_record, :purpose, :period, :is_deleted)
  end



end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "ゲストでログインしました。"
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>ユーザーデータ</h2>

    <%= form_with model: [:admin, @user], local: true do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
        </div>

        <div class="form-group">
        <%= f.label :nationality %>
        <%= f.country_select :country_code %>
      </div>

      <div class="form-group">
        <%= f.label :abroad_record %>
        <%= f.text_field :abroad_record, class: "form-control name" %>
      </div>

      <div class="form-group">
        <%= f.label :purpose %>
        <%= f.text_field :purpose, class: "form-control name" %>
      </div>

      <div class="form-group">
        <%= f.label :period %>
        <%= f.text_field :period, class: "form-control name" %>
      </div>

      <div>
      <%= f.label :is_deleted, '有効', value: false %>
     <%= f.radio_button :is_deleted, 'false' %>
     <%= f.label :is_deleted, '無効', value: true %>
     <%= f.radio_button :is_deleted, 'true' %>
      </div>

      <div class="form-group">
        <%= f.submit class: "btn btn-secondary" %>
      </div>


      <!--<div><%#= link_to "退会する",  unsubscribe_path %></div>-->
    <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
 <h4><span class="bg-light bg-gradient">登録ユーザー</span></h4>
<table class='table'>
  <thead>
    <tr>
      <th>アイコン</th>
      <th>名前</th>
      <th>ステータス</th>
      <th>編集</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, class: "rounded-circle border border-dark", size:'30x30' %></td>
        <td><%= user.name %></td>
        <td>
          <% if user.is_deleted == false %>
            有効
          <% else %>
            無効
          <% end %>
        </td>
        <td><%= link_to 'ユーザー編集', edit_admin_user_path(user.id), class:"btn btn-info" %></td>
    <% end %>
  </tbody>
</table>
 <div class="paginattion">
        <%= paginate @users %>
  </div>

app/views/admin/users/show.html.erb
<h1>Admin::Users#show</h1>
<p>Find me in app/views/admin/users/show.html.erb</p>