config/routes.rb
Rails.application.routes.draw do


  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end


  # ユーザー用
# URL /user/sign_in ...
devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: "public/sessions"
}


 scope module: :public do
  root to: "homes#top"
  get "/home/about" => "homes#about", as: "about"
  get "relationships/followings"
  get "relationships/followers"
  get "/article/hashtag/:name", to: "articles#hashtag"
  get "search" => "searches#search"
  get "users/unsubscribe" => "users#unsubscribe", as: "unsubscribe"
  patch "users/withdrawal" => "users#withdrawal", as: "withdrawal"
  get "chat/:id" => "chats#show", as: "chat"
  resources :chats, only: [:create]


 resources :articles, only: [:new,:index,:show,:edit,:create,:destroy,:update] do
   resources :article_comments, only:[:create, :destroy]
   resource :favorites, only: [:create, :destroy,]
 end

  resources :users, only: [:index,:show,:edit,:update] do
     member do
      get :favorites
    end
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
 end

end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
   root to: "homes#top"
   resources :articles, only: [:index, :show, :edit, :update, :destroy]
   resources :users, only: [:index, :show, :edit, :update]
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger text-center" role="alert">
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
   <div class="flash"><%= flash[:notice] %></div>
<% end %>

<script>
  $(function() {
    setTimeout("$('.flash').fadeOut('slow')", 2000);
  });
</script>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Abboo.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Abboo</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <%= render 'public/searches/search' %>
        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%=  link_to users_path,class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> Users
            <% end %>
          </li>
          <li>
            <%=  link_to articles_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> Articles
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' }, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> Log out
            <% end %>
          </li>
          
          
           <% elsif admin_signed_in? %>
          <li>
            <%= link_to admin_root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%=  link_to admin_users_path,class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> Users
            <% end %>
          </li>
          <li>
            <%=  link_to admin_articles_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> Articles
            <% end %>
          </li>
          <li>
            <%= link_to destroy_admin_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> Log out
            <% end %>
          </li>
          
        <% else %>
          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%= link_to about_path,class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> About
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> Sign up
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> Log in
            <% end %>
          </li>
        <% end %>
        </ul>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Abboo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<!--Google APIによる影響でturbolinksをoffにする設定-->
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome-animation/0.0.10/font-awesome-animation.css" type="text/css" media="all" />
  </head>

  <body>
     <%= render 'layouts/header' %>
     <%= render 'layouts/flash' %>
     <%= yield %>
     <%= render 'layouts/footer' %>
  </body>
</html>